# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "$text"
background = "$base"
dim_foreground = "$subtle"
bright_foreground = "$text"

[colors.cursor]
text = "$base"
cursor = "$text"

[colors.vi_mode_cursor]
text = "$base"
cursor = "$text"

[colors.search.matches]
foreground = "$subtle"
background = "$overlay"

[colors.search.focused_match]
foreground = "$base"
background = "$rose"

[colors.hints.start]
foreground = "$subtle"
background = "$surface"

[colors.hints.end]
foreground = "$muted"
background = "$surface"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "$text"
background = "$surface"

[colors.selection]
text = "$text"
background = "$highlightMed"

[colors.normal]
black = "$black"
red = "$red"
green = "$green"
yellow = "$yellow"
blue = "$blue"
magenta = "$magenta"
cyan = "$cyan"
white = "$white"

[colors.bright]
black = "$brightBlack"
red = "$brightRed"
green = "$brightGreen"
yellow = "$brightYellow"
blue = "$brightBlue"
magenta = "$brightMagenta"
cyan = "$brightCyan"
white = "$brightWhite"

[colors.dim]
black = "$black"
red = "$red"
green = "$green"
yellow = "$yellow"
blue = "$blue"
magenta = "$magenta"
cyan = "$cyan"
white = "$white"

